export type CalculatorStatus = "planned" | "building" | "published";

export interface CalculatorRegistryItem {
  id: string;
  name: string;
  category: "solar" | "battery" | "home-energy" | "ev";
  route: string;
  phase: 1 | 2 | 3 | 4 | 5;
  status: CalculatorStatus;
  primaryKeyword: string;
  seoTitle: string;
  metaDescription: string;
  relatedCalculatorIds: string[];
}

export const calculatorRegistry: CalculatorRegistryItem[] = [
  {
    id: "ev-charging-time",
    name: "EV Charging Time Calculator",
    category: "ev",
    route: "/ev/ev-charging-time-calculator",
    phase: 1,
    status: "published",
    primaryKeyword: "ev charging time calculator",
    seoTitle: "EV Charging Time Calculator — AC & DC Charge Time",
    metaDescription: "Estimate EV charging time from battery capacity, start and target charge, charger power and vehicle limits with clear AC and DC assumptions.",
    relatedCalculatorIds: [],
  },
  {
    id: "ev-charging-cost",
    name: "EV Charging Cost Calculator",
    category: "ev",
    route: "/ev/ev-charging-cost-calculator",
    phase: 3,
    status: "published",
    primaryKeyword: "ev charging cost calculator",
    seoTitle: "EV Charging Cost Calculator — Cost per Charge",
    metaDescription: "Estimate EV charging cost from usable battery capacity, battery-side consumption, charging efficiency and your electricity price per kWh.",
    relatedCalculatorIds: ["ev-charging-time"],
  },
  {
    id: "ev-range",
    name: "EV Range Calculator",
    category: "ev",
    route: "/ev/ev-range-calculator",
    phase: 4,
    status: "published",
    primaryKeyword: "ev range calculator",
    seoTitle: "EV Range Calculator — Estimate Real-World Range",
    metaDescription: "Estimate EV range from usable battery capacity, state of charge, reserve, battery health and consumption in kWh/100 km or mi/kWh.",
    relatedCalculatorIds: ["ev-charging-time", "ev-charging-cost"],
  },
  {
    id: "ev-savings",
    name: "EV Savings Calculator",
    category: "ev",
    route: "/ev/ev-savings-calculator",
    phase: 4,
    status: "published",
    primaryKeyword: "ev savings calculator",
    seoTitle: "EV Savings Calculator — Compare Electricity vs Fuel Cost",
    metaDescription: "Compare EV electricity cost with combustion-vehicle fuel cost using your annual distance, EV consumption, electricity price, fuel economy and fuel price.",
    relatedCalculatorIds: ["ev-range", "ev-charging-cost"],
  },
  {
    id: "electricity-usage",
    name: "Electricity Usage Calculator",
    category: "home-energy",
    route: "/home-energy/electricity-usage-calculator",
    phase: 1,
    status: "published",
    primaryKeyword: "electricity usage calculator",
    seoTitle: "Electricity Usage Calculator — kWh by Appliance & Home",
    metaDescription: "Estimate daily, monthly and annual electricity use from appliance watts, schedules, cycles or energy-label values with editable assumptions.",
    relatedCalculatorIds: [],
  },
  {
    id: "energy-bill",
    name: "Energy Bill Calculator",
    category: "home-energy",
    route: "/home-energy/energy-bill-calculator",
    phase: 3,
    status: "published",
    primaryKeyword: "energy bill calculator",
    seoTitle: "Energy Bill Calculator — Estimate Electricity Cost",
    metaDescription: "Estimate an electricity bill from kWh usage and your own electricity price with optional fixed charges, standing charges and tax.",
    relatedCalculatorIds: ["electricity-usage"],
  },
  {
    id: "solar-panel-tilt",
    name: "Solar Panel Tilt Calculator",
    category: "solar",
    route: "/solar/solar-panel-tilt-calculator",
    phase: 1,
    status: "published",
    primaryKeyword: "solar panel tilt calculator",
    seoTitle: "Solar Panel Tilt Calculator — Find the Best Angle",
    metaDescription: "Calculate a solar panel tilt starting point from your location, then compare roof angles with modeled annual and monthly solar production.",
    relatedCalculatorIds: [],
  },
  {
    id: "solar-panel-output",
    name: "Solar Panel Output Calculator",
    category: "solar",
    route: "/solar/solar-panel-output-calculator",
    phase: 2,
    status: "published",
    primaryKeyword: "solar panel output calculator",
    seoTitle: "Solar Panel Output Calculator — Estimate kWh Production",
    metaDescription: "Estimate monthly and annual solar panel output from system size, location, tilt, azimuth and losses using a location-aware PVWatts model.",
    relatedCalculatorIds: ["solar-panel-tilt"],
  },
  {
    id: "solar-battery-bank-size",
    name: "Solar Battery Bank Size Calculator",
    category: "solar",
    route: "/solar/solar-battery-bank-size-calculator",
    phase: 3,
    status: "published",
    primaryKeyword: "solar battery calculator",
    seoTitle: "Solar Battery Calculator — Size a Battery Bank",
    metaDescription: "Estimate solar battery bank size from daily load, autonomy, SOC, inverter efficiency, battery health and planning margin.",
    relatedCalculatorIds: ["solar-panel-output", "electricity-usage"],
  },
  {
    id: "solar-load",
    name: "Solar Load Calculator",
    category: "solar",
    route: "/solar/solar-load-calculator",
    phase: 3,
    status: "published",
    primaryKeyword: "solar load calculator",
    seoTitle: "Solar Load Calculator — Estimate Daily Appliance Energy",
    metaDescription: "Estimate daily solar load energy from appliance watts, schedules, duty-cycle assumptions and essential-load planning.",
    relatedCalculatorIds: ["solar-battery-bank-size", "solar-panel-size", "electricity-usage"],
  },
  {
    id: "solar-panel-size",
    name: "Solar Panel Size Calculator",
    category: "solar",
    route: "/solar/solar-panel-size-calculator",
    phase: 2,
    status: "published",
    primaryKeyword: "solar panel size calculator",
    seoTitle: "Solar Panel Size Calculator — System kW & Panel Count",
    metaDescription: "Estimate solar system size and panel count from your energy target, location, panel wattage, tilt and modeled solar yield.",
    relatedCalculatorIds: ["solar-panel-output", "solar-panel-tilt", "solar-battery-bank-size"],
  },
  {
    id: "battery-runtime",
    name: "Battery Runtime Calculator",
    category: "battery",
    route: "/battery/battery-runtime-calculator",
    phase: 1,
    status: "published",
    primaryKeyword: "battery runtime calculator",
    seoTitle: "Battery Runtime Calculator — Estimate Backup Time",
    metaDescription: "Estimate battery runtime from Wh or Ah, voltage, load, state of charge, reserve and inverter efficiency. See usable energy, assumptions and runtime scenarios.",
    relatedCalculatorIds: ["battery-size"],
  },
  {
    id: "battery-size",
    name: "Battery Size Calculator",
    category: "battery",
    route: "/battery/battery-size-calculator",
    phase: 1,
    status: "published",
    primaryKeyword: "battery size calculator",
    seoTitle: "Battery Size Calculator — kWh & Ah for Backup Power",
    metaDescription: "Calculate battery capacity for a load and backup time.",
    relatedCalculatorIds: ["battery-runtime"],
  },
  {
    id: "ups-runtime",
    name: "UPS Runtime Calculator",
    category: "battery",
    route: "/battery/ups-runtime-calculator",
    phase: 2,
    status: "published",
    primaryKeyword: "ups runtime calculator",
    seoTitle: "UPS Runtime Calculator — Estimate Backup Time",
    metaDescription: "Estimate UPS backup runtime from battery energy, load watts, usable energy, battery health and UPS efficiency.",
    relatedCalculatorIds: [],
  },
  {
    id: "ups-battery-size",
    name: "UPS Battery Size Calculator",
    category: "battery",
    route: "/battery/ups-battery-size-calculator",
    phase: 2,
    status: "published",
    primaryKeyword: "ups battery size calculator",
    seoTitle: "UPS Battery Size Calculator — Wh & Ah for Backup Time",
    metaDescription: "Calculate UPS battery size from load watts and required backup time, including UPS efficiency, usable battery fraction, health and planning margin.",
    relatedCalculatorIds: ["ups-runtime"],
  },
  {
    id: "battery-capacity",
    name: "Battery Capacity Calculator",
    category: "battery",
    route: "/battery/battery-capacity-calculator",
    phase: 2,
    status: "published",
    primaryKeyword: "battery capacity calculator",
    seoTitle: "Battery Capacity Calculator — Convert Ah, Wh & kWh",
    metaDescription: "Convert battery capacity between amp-hours, watt-hours and kWh using voltage, and estimate usable energy from state of charge, reserve and battery health.",
    relatedCalculatorIds: ["battery-runtime"],
  },
  {
    id: "battery-charging-time",
    name: "Battery Charging Time Calculator",
    category: "battery",
    route: "/battery/battery-charging-time-calculator",
    phase: 2,
    status: "published",
    primaryKeyword: "battery charging time calculator",
    seoTitle: "Battery Charging Time Calculator — Estimate Charge Time",
    metaDescription: "Estimate battery charging time from capacity, state of charge and charger output, with optional battery limits, efficiency and planning assumptions.",
    relatedCalculatorIds: ["battery-capacity", "battery-runtime"],
  },
  {
    id: "home-battery-size",
    name: "Home Battery Size Calculator",
    category: "home-energy",
    route: "/home-energy/home-battery-size-calculator",
    phase: 3,
    status: "published",
    primaryKeyword: "home battery size calculator",
    seoTitle: "Home Battery Size Calculator — Backup kWh Estimate",
    metaDescription: "Estimate home battery size from household energy, backup scope, backup hours, reserve, inverter efficiency and planning margin.",
    relatedCalculatorIds: ["electricity-usage", "solar-battery-bank-size"],
  },
  {
    id: "portable-power-station",
    name: "Portable Power Station Calculator",
    category: "battery",
    route: "/battery/portable-power-station-calculator",
    phase: 4,
    status: "published",
    primaryKeyword: "portable power station calculator",
    seoTitle: "Portable Power Station Calculator — Runtime & Capacity",
    metaDescription: "Estimate portable power station runtime from Wh capacity and appliance load, or calculate the capacity needed for a target runtime. Check AC output limits.",
    relatedCalculatorIds: ["battery-runtime", "electricity-usage", "solar-load"],
  },
  {
    id: "appliance-wattage",
    name: "Appliance Wattage Calculator",
    category: "home-energy",
    route: "/home-energy/appliance-wattage-calculator",
    phase: 4,
    status: "published",
    primaryKeyword: "appliance wattage calculator",
    seoTitle: "Appliance Wattage Calculator — Estimate Watts & kWh",
    metaDescription: "Estimate appliance running watts from editable presets or your device label, then calculate energy use for a selected runtime. Use the result in battery or solar tools.",
    relatedCalculatorIds: ["electricity-usage", "battery-runtime", "solar-load"],
  },
  {
    id: "voltage-drop",
    name: "Voltage Drop Calculator",
    category: "battery",
    route: "/battery/voltage-drop-calculator",
    phase: 5,
    status: "published",
    primaryKeyword: "voltage drop calculator",
    seoTitle: "Voltage Drop Calculator — DC & AC Wire Size Sizing",
    metaDescription: "Calculate DC & AC voltage drop percentage, power loss in watts, and recommended wire gauge (AWG / mm²) for 12V, 24V, 48V, 120V, and 240V circuits to meet NEC 3% limits.",
    relatedCalculatorIds: ["battery-size", "battery-runtime"],
  },
  {
    id: "generator-size",
    name: "Generator Size Calculator",
    category: "home-energy",
    route: "/home-energy/generator-size-calculator",
    phase: 5,
    status: "published",
    primaryKeyword: "generator size calculator",
    seoTitle: "Generator Size Calculator — Running & Starting Watts",
    metaDescription: "Calculate the exact generator size (running and starting watts) needed for your home, RV, or jobsite appliances. Find the right portable or standby generator capacity.",
    relatedCalculatorIds: ["home-battery-size", "electricity-usage", "appliance-wattage"],
  },
  {
    id: "solar-payback",
    name: "Solar Payback Calculator",
    category: "solar",
    route: "/solar/solar-payback-calculator",
    phase: 5,
    status: "published",
    primaryKeyword: "solar payback calculator",
    seoTitle: "Solar Payback Calculator — Break-Even Period & ROI",
    metaDescription: "Calculate your solar payback period in years, return on investment (ROI), and 25-year lifetime savings based on system cost, annual production, and utility rates.",
    relatedCalculatorIds: ["solar-panel-output", "energy-bill", "solar-battery-bank-size"],
  },
  {
    id: "ac-cost",
    name: "Air Conditioner Cost Calculator",
    category: "home-energy",
    route: "/home-energy/air-conditioner-cost-calculator",
    phase: 5,
    status: "published",
    primaryKeyword: "air conditioner electricity cost calculator",
    seoTitle: "Air Conditioner Electricity Cost Calculator — Hourly & Monthly AC Cost",
    metaDescription: "Calculate how much your air conditioner costs to run per hour, day, and month. Estimate electricity costs for window units, mini-splits, and central AC by SEER2 rating.",
    relatedCalculatorIds: ["electricity-usage", "energy-bill", "heat-pump-cost"],
  },
  {
    id: "space-heater-cost",
    name: "Space Heater Cost Calculator",
    category: "home-energy",
    route: "/home-energy/space-heater-cost-calculator",
    phase: 5,
    status: "published",
    primaryKeyword: "space heater electricity cost calculator",
    seoTitle: "Space Heater Electricity Cost Calculator — Hourly & Nightly Running Cost",
    metaDescription: "Calculate how much your electric space heater costs to run per hour, 8-hour night, and month. See exact electricity costs for 500W, 1000W, and 1500W heaters.",
    relatedCalculatorIds: ["electricity-usage", "energy-bill", "appliance-wattage"],
  },
  {
    id: "heat-pump-cost",
    name: "Heat Pump Running Cost Calculator",
    category: "home-energy",
    route: "/home-energy/heat-pump-cost-calculator",
    phase: 5,
    status: "published",
    primaryKeyword: "heat pump running cost calculator",
    seoTitle: "Heat Pump Running Cost Calculator — Heat Pump vs Gas Comparison",
    metaDescription: "Compare heat pump operating costs vs natural gas, propane, or oil furnaces. Calculate annual heating bill savings based on COP/HSPF2, AFUE, and local fuel prices.",
    relatedCalculatorIds: ["ac-cost", "electricity-usage", "energy-bill"],
  },
  {
    id: "solar-charge-controller",
    name: "Solar Charge Controller Calculator",
    category: "solar",
    route: "/solar/solar-charge-controller-calculator",
    phase: 5,
    status: "published",
    primaryKeyword: "solar charge controller calculator",
    seoTitle: "Solar Charge Controller Calculator — MPPT & PWM Sizing",
    metaDescription: "Size the right MPPT or PWM solar charge controller for your panels and battery bank. Calculate required output current (Amps) and cold-weather array voltage (Voc).",
    relatedCalculatorIds: ["solar-battery-bank-size", "voltage-drop", "solar-panel-output"],
  },
  {
    id: "inverter-size",
    name: "Inverter Size Calculator",
    category: "battery",
    route: "/battery/inverter-size-calculator",
    phase: 5,
    status: "published",
    primaryKeyword: "inverter size calculator",
    seoTitle: "Inverter Size Calculator — Continuous & Surge Watts Sizing",
    metaDescription: "Calculate the exact inverter size in continuous and surge watts needed to run your appliances from a battery. Find the right 12V, 24V, or 48V inverter capacity.",
    relatedCalculatorIds: ["battery-size", "voltage-drop", "battery-runtime"],
  },
  {
    id: "v2l-runtime",
    name: "V2L Runtime Calculator",
    category: "ev",
    route: "/ev/v2l-runtime-calculator",
    phase: 5,
    status: "published",
    primaryKeyword: "v2l calculator",
    seoTitle: "Vehicle-to-Load (V2L) Runtime Calculator — EV Emergency Power Duration",
    metaDescription: "Calculate how many days your EV battery can power your home and appliances using Vehicle-to-Load (V2L) or V2H. Includes driving range reserve and continuous AC power limits.",
    relatedCalculatorIds: ["ev-range", "home-battery-size", "battery-runtime"],
  },
  {
    id: "ev-breaker-size",
    name: "EV Charger Breaker Size Calculator",
    category: "ev",
    route: "/ev/ev-charger-breaker-size-calculator",
    phase: 5,
    status: "published",
    primaryKeyword: "ev charger breaker size calculator",
    seoTitle: "EV Charger Breaker & Wire Size Calculator — Level 2 Sizing",
    metaDescription: "Find the exact circuit breaker size, wire gauge (AWG), and charging speed (kW) for your home Level 2 EV charger following the NEC 125% continuous load rule.",
    relatedCalculatorIds: ["ev-charging-time", "voltage-drop", "ev-charging-cost"],
  },
];

export const publishedCalculators = () =>
  calculatorRegistry.filter((calculator) => calculator.status === "published");

export const isCalculatorPublished = (id: string) =>
  calculatorRegistry.some((calculator) => calculator.id === id && calculator.status === "published");
