"use client";

import { useState } from "react";
import { siteConfig } from "@/lib/site-config";

export interface DerivationStep {
  stepNumber: number;
  name: string;
  formulaLatex: string;
  substitutedLatex: string;
  explanation: string;
  resultValue?: string;
}

interface MathDerivationInspectorProps {
  title?: string;
  toolName: string;
  canonicalRoute: string;
  steps: DerivationStep[];
  standards?: string[];
  assumptions?: Array<{ label: string; value: string | number; unit?: string }>;
}

export function MathDerivationInspector({
  title = "Step-by-Step Mathematical Derivation & Proof",
  toolName,
  canonicalRoute,
  steps,
  standards = ["IEEE Std 485", "NFPA 70 NEC", "NREL SAM", "ASHRAE 90.1"],
  assumptions = [],
}: MathDerivationInspectorProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [copiedLlm, setCopiedLlm] = useState(false);

  const fullUrl = `${siteConfig.url.replace(/\/$/, "")}${canonicalRoute.startsWith("/") ? canonicalRoute : `/${canonicalRoute}`}`;

  const generateLlmPrompt = () => {
    let md = `### PowerLab Calculation Scenario: ${toolName}\n\n`;
    md += `**Canonical Tool Source:** ${fullUrl}\n`;
    md += `**Engineering Standards Cited:** ${standards.join(", ")}\n\n`;

    if (assumptions.length > 0) {
      md += `#### Input Assumptions:\n`;
      assumptions.forEach((a) => {
        md += `- **${a.label}:** ${a.value} ${a.unit || ""}\n`;
      });
      md += `\n`;
    }

    md += `#### Deterministic Step-by-Step Mathematical Derivation:\n`;
    steps.forEach((s) => {
      md += `**Step ${s.stepNumber}: ${s.name}**\n`;
      md += `- Formula: \`${s.formulaLatex}\`\n`;
      md += `- Substituted Values: \`${s.substitutedLatex}\`\n`;
      if (s.resultValue) md += `- Result: **${s.resultValue}**\n`;
      md += `- Explanation: ${s.explanation}\n\n`;
    });

    md += `*Generated by PowerLab Deterministic Open Energy Model (CC BY 4.0)*\n`;
    return md;
  };

  const handleCopyLlm = async () => {
    try {
      const text = generateLlmPrompt();
      await navigator.clipboard.writeText(text);
      setCopiedLlm(true);
      setTimeout(() => setCopiedLlm(false), 2500);
    } catch {
      setCopiedLlm(false);
    }
  };

  return (
    <div
      style={{
        marginTop: "1.5rem",
        borderRadius: "0.85rem",
        border: "1px solid var(--line, #e2e8f0)",
        background: "var(--surface, #ffffff)",
        overflow: "hidden",
      }}
    >
      <div
        onClick={() => setIsOpen(!isOpen)}
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          padding: "1rem 1.25rem",
          cursor: "pointer",
          background: isOpen ? "var(--surface-subtle, #f8fafc)" : "transparent",
          userSelect: "none",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "0.6rem" }}>
          <span style={{ fontSize: "1.15rem" }}>🔬</span>
          <div>
            <span style={{ fontWeight: 700, fontSize: "0.98rem", color: "var(--brand-strong)" }}>
              {title}
            </span>
            <span style={{ display: "block", fontSize: "0.78rem", color: "var(--muted)" }}>
              Inspect exact intermediate variables, physical loss deratings &amp; LaTeX proofs
            </span>
          </div>
        </div>
        <span style={{ fontSize: "1rem", color: "var(--muted)", fontWeight: 700 }}>
          {isOpen ? "▲ Hide" : "▼ Show Proof"}
        </span>
      </div>

      {isOpen && (
        <div style={{ padding: "1.25rem", borderTop: "1px solid var(--line, #e2e8f0)" }}>
          {/* Action Bar for AI Copy */}
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: "0.75rem", marginBottom: "1.25rem", paddingBottom: "1rem", borderBottom: "1px solid var(--line)" }}>
            <span style={{ fontSize: "0.82rem", color: "var(--muted)" }}>
              Standard: <strong>{standards.join(" &bull; ")}</strong>
            </span>
            <button
              type="button"
              onClick={handleCopyLlm}
              className="button secondary-button"
              style={{ fontSize: "0.82rem", padding: "0.35rem 0.85rem", display: "inline-flex", alignItems: "center", gap: "0.35rem" }}
            >
              {copiedLlm ? "✅ Copied for LLM!" : "🤖 Copy Scenario for ChatGPT / Claude / Perplexity"}
            </button>
          </div>

          {/* Sequential Step Cards */}
          <div style={{ display: "grid", gap: "1rem" }}>
            {steps.map((step) => (
              <div
                key={step.stepNumber}
                style={{
                  padding: "1rem",
                  borderRadius: "0.65rem",
                  background: "var(--surface-subtle, #f8fafc)",
                  border: "1px solid var(--line)",
                }}
              >
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "0.35rem" }}>
                  <span style={{ fontSize: "0.82rem", fontWeight: 800, color: "var(--brand-strong)", textTransform: "uppercase" }}>
                    Step {step.stepNumber}: {step.name}
                  </span>
                  {step.resultValue && (
                    <span style={{ fontSize: "0.85rem", fontWeight: 700, color: "#16a34a" }}>
                      = {step.resultValue}
                    </span>
                  )}
                </div>

                <div style={{ display: "grid", gap: "0.35rem", margin: "0.5rem 0" }}>
                  <div style={{ fontSize: "0.8rem", color: "var(--muted)" }}>Formula:</div>
                  <pre className="math-block" style={{ padding: "0.5rem 0.75rem", background: "var(--surface)", borderRadius: "0.4rem", border: "1px solid var(--line)", overflowX: "auto", margin: 0, fontSize: "0.88rem" }}>
                    <code>{step.formulaLatex}</code>
                  </pre>

                  <div style={{ fontSize: "0.8rem", color: "var(--muted)", marginTop: "0.25rem" }}>Substituted Values:</div>
                  <pre className="math-block" style={{ padding: "0.5rem 0.75rem", background: "var(--surface)", borderRadius: "0.4rem", border: "1px solid var(--line)", overflowX: "auto", margin: 0, fontSize: "0.88rem" }}>
                    <code>{step.substitutedLatex}</code>
                  </pre>
                </div>

                <p style={{ margin: "0.5rem 0 0", fontSize: "0.85rem", color: "var(--ink)", lineHeight: 1.5 }}>
                  {step.explanation}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
